const SIGNED_IN = 'SIGNED_IN'
const NOT_SIGNED_IN = 'NOT_SIGNED_IN'

// Profile
// const PROFILE_FETCHED = 'PROFILE_FETCHED'
// const PROFILE_EMPTY = 'PROFILE_EMPTY'
// const PROFILE_CREATED_SUCCESSFUL = 'PROFILE_CREATED_SUCCESSFUL'
// const PROFILE_CREATED_FAILED = 'PROFILE_CREATED_FAILED'
// const CLEAR_PROFILE = 'CLEAR_PROFILE'
// const UPDATE_PROFILE_SUCCESSFUL = 'UPDATE_PROFILE_SUCCESSFUL'
// const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'
// const UPLOAD_AVATAR_SUCCESSFUL = 'UPLOAD_AVATAR_SUCCESSFUL'
// const UPLOAD_AVATAR_FAILED = 'UPLOAD_AVATAR_FAILED'

// Error types
const SERVER_ERROR = 'SERVER_ERROR'
const AUTH_SERVER_ERROR = 'AUTH_SERVER_ERROR'

export {
  SIGNED_IN,
  NOT_SIGNED_IN,
  AUTH_SERVER_ERROR,
  SERVER_ERROR
}
